### ISSUE TITLE
Use Popper for dropdown positioning

### ISSUE THREAD

**Issue by oyejorge** [orchidjs/orchid-select#6]

**Comment by marmaak** [comment]
Hi @oyejorge, first of all congrats for this fantastic library, I think is one of the most complete and customizable you can find on npm :)

Is there a chance you'll be able to re-open this issue? Can I help somehow? I'm already familiar with popper and tippy and maybe I can think about create a PR or suggest you how to integrate popper

Cheers

**Comment by oyejorge** [comment]
I'm wondering if it needs to be integrated or left as an option. There was [another discussion](https://github.com/orchidjs/tom-select/discussions/163) about opening the dropdown above and [here's what I proposed](https://jsfiddle.net/ok56a0gu/).

**Comment by oyejorge** [comment]
> Well, my only point is that if you have a field that is near to the bottom edge of the viewport and you try to open the select the list will be shown truncated (or even worst not visibile at all) 

Which is solved with the example I shared right?

> I don't want to set the dropdownParent to body

Not sure what you're referring to here. Why would you need to set the dropdownParent to body?

> If the idea is to keep the library as much standalone as possible, that's fair enough

It think the standalone approach is appropriate. I'm not opposed to a plugin though.
